AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ComputelessBlog

Globals:
  Api:
    OpenApiVersion: "3.0.1"

Mappings:
  ResponseTemplates:
    Page:
      Fn::Transform:
        Name: AWS::Include
        Parameters:
          Location: 'page.yaml'

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref AWS::StackName
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      LocalSecondaryIndexes:
        - IndexName: ItemTypeByDate
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  RestAPIRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: RestAPIPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - dynamodb:Query
                Resource:
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}
                - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTable}/*

  RestAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: './openapi.yaml'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: apiGatewayRestApi
            DomainName: !Sub ${RestAPI}.execute-api.${AWS::Region}.amazonaws.com
            OriginPath: /Prod
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        Enabled: true
        DefaultCacheBehavior:
          Compress: True
          ForwardedValues:
            QueryString: false
          DefaultTTL: 600 # in seconds (600 = 10 minutes)
          TargetOriginId: apiGatewayRestApi
          ViewerProtocolPolicy: redirect-to-https

Outputs:
  WebSiteOrigin:
    Value: !Sub https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod

  CloudFrontDistribution:
    Value: !Sub https://${CloudFrontDistribution.DomainName}/
